CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    priority VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    due_date DATE,
    estimated_minutes INTEGER,
    CONSTRAINT pk_tasks PRIMARY KEY (id),
    CONSTRAINT fk_tasks_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE INDEX idx_tasks_owner_id ON tasks (owner_id);

CREATE TABLE daily_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id BIGINT NOT NULL,
    plan_date DATE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    available_minutes INTEGER,
    warning JSONB,
    CONSTRAINT pk_daily_plans PRIMARY KEY (id),
    CONSTRAINT fk_daily_plans_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE INDEX idx_daily_plans_owner_id_plan_date ON daily_plans (owner_id, plan_date);
CREATE INDEX idx_daily_plans_owner_id_created_at_id ON daily_plans (owner_id, created_at, id);

CREATE TABLE daily_plan_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    daily_plan_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    CONSTRAINT pk_daily_plan_items PRIMARY KEY (id),
    CONSTRAINT fk_daily_plan_items_daily_plan FOREIGN KEY (daily_plan_id) REFERENCES daily_plans (id),
    CONSTRAINT fk_daily_plan_items_task FOREIGN KEY (task_id) REFERENCES tasks (id)
);

CREATE INDEX idx_daily_plan_items_daily_plan_id ON daily_plan_items (daily_plan_id);
