CREATE TABLE scheduling_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id BIGINT NOT NULL,
    work_day_start TIME(0) NOT NULL,
    work_day_end TIME(0) NOT NULL,
    cadence_enabled BOOLEAN NOT NULL,
    target_focus_minutes INTEGER NOT NULL,
    break_minutes INTEGER NOT NULL,
    min_session_minutes INTEGER NOT NULL,
    buffer_minutes INTEGER NOT NULL,
    peak_start TIME(0),
    peak_end TIME(0),
    CONSTRAINT pk_scheduling_preferences PRIMARY KEY (id),
    CONSTRAINT uk_scheduling_preferences_owner UNIQUE (owner_id)
);

CREATE TABLE fixed_breaks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    scheduling_preferences_id BIGINT NOT NULL,
    label VARCHAR(255) NOT NULL,
    start_time TIME(0) NOT NULL,
    end_time TIME(0) NOT NULL,
    CONSTRAINT pk_fixed_breaks PRIMARY KEY (id),
    CONSTRAINT fk_fixed_breaks_scheduling_preferences
        FOREIGN KEY (scheduling_preferences_id) REFERENCES scheduling_preferences (id)
);

CREATE TABLE commitments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    commitment_date DATE NOT NULL,
    start_time TIME(0) NOT NULL,
    end_time TIME(0) NOT NULL,
    CONSTRAINT pk_commitments PRIMARY KEY (id),
    CONSTRAINT fk_commitments_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE INDEX idx_commitments_owner_id_commitment_date ON commitments (owner_id, commitment_date);

UPDATE tasks SET estimated_minutes = NULL WHERE estimated_minutes <= 0;

ALTER TABLE tasks
    ADD CONSTRAINT ck_tasks_estimated_minutes_positive
        CHECK (estimated_minutes IS NULL OR estimated_minutes > 0);
